const char wifiSetupHtml[] PROGMEM = "<!DOCTYPE html>\n"
    "<html>\n"
        "<head>\n"
        "<title>WLAN-Einrichtung</title>\n"
        "</head>\n"
        "<body>\n"
            "<h1>Initiale WLAN-Einrichtung</h1>\n"
            "<form action='/'>\n"
                "SSID: <input type='text' name='ssid'><br/><br />\n"
                "Passwort: <input type='text' name='pw'><br /><br />\n"
                "<input type='submit' value='Absenden'>\n"
            "</form>\n"
            "<br /><br />\n"
            "<form action='/restart'>\n"
                "<input type='submit' value='Neustart'>\n"
            "</form>\n"
        "</body>\n"
    "</html>\n";