name: Build all boards
on:
  push:
    branches:    
      - master

jobs:
  main:
    name: Build all boards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip3 install -U platformio
      - name: Build
        run: platformio run -e esp32-a1s -e lolin32 -e lolin_d32 -e lolin_d32_pro -e nodemcu-32s -e az-delivery-devkit-v4 -e ttgo_t8
