name: clang-format Check
on: [push, pull_request]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.18.0
        with:
          clang-format-version: "16"
          check-path: "src"
          fallback-style: "LLVM" # optional
