name: build-all
run-name: Build all boards
on:
  workflow_dispatch:
  push:
  pull_request:
    paths:
      - 'src/*'
      - 'html/*'
      - 'test/*'
      - '**.ini'
      - '**.py'
      - '**.csv'

jobs:
  test_builds:
    name: Run all Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - lolin_d32_pro
          - lolin_d32_pro_sdmmc_pe
          - ttgo_t8
          - complete

    steps:
      - uses: actions/checkout@v5
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: |
          pip install -U setuptools platformio
          pio upgrade --dev
          pio pkg update --global
      - name: Build ${{ matrix.variant }} for RC522
        run: platformio run -e ${{ matrix.variant }}
      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-RC522-${{ matrix.variant }}.bin
          path: .pio/build/${{ matrix.variant }}/firmware.bin
      - name: Change RFID type
        run: |
          sed -i 's/\/\/#define RFID_READER_TYPE_PN5180/#define RFID_READER_TYPE_PN5180/' src/settings.h
          sed -i 's/#define RFID_READER_TYPE_MFRC522_SPI/\/\/#define RFID_READER_TYPE_MFRC522_SPI/' src/settings.h
      - name: Build ${{ matrix.variant }} for PN5180
        run: platformio run -e ${{ matrix.variant }}
      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-PN5180-${{ matrix.variant }}.bin
          path: .pio/build/${{ matrix.variant }}/firmware.bin
